services:
  postgres-admin:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=locki-admin'
      - 'POSTGRES_PASSWORD=locki'
      - 'POSTGRES_USER=locki'
    ports:
      - '5450:5432'
    networks:
      - locki-net
  postgres-reservations:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=locki-reservations'
      - 'POSTGRES_PASSWORD=locki'
      - 'POSTGRES_USER=locki'
    ports:
      - '5460:5432'
    networks:
      - locki-net
  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'
    networks:
      - locki-net

networks:
  locki-net:
    name: locki-net