<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ferdonof</groupId>
        <artifactId>manage-administration</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>manage-administration-rest-endpoints</artifactId>
    <packaging>pom</packaging>
    <name>${project.groupId}:${project.artifactId}</name>
    <modules>
        <module>boot</module>
        <module>locations-rest-endpoints</module>
        <module>lockers-rest-endpoints</module>
        <module>racks-rest-endpoints</module>
        <module>users-rest-endpoints</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.ferdonof</groupId>
            <artifactId>manage-administration-domain</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ferdonof</groupId>
            <artifactId>manage-administration-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.ferdonof</groupId>
            <artifactId>manage-administration-infrastructure-repository-psql</artifactId>
        </dependency>

        <dependency>
          <groupId>com.ferdonof.locki</groupId>
          <artifactId>admin-rest-spec</artifactId>
          <version>${admin-rest-spec.version}</version>
        </dependency>


        <!-- DEPENDENCIES FOR REST ENDPOINTS -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
        </dependency>
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
    </dependencies>


    <build>
        <plugins>
            <!-- UNPACK APIs -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>unpack-incidence-rest-api</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.ferdonof.locki</groupId>
                                    <artifactId>admin-rest-spec</artifactId>
                                    <version>${admin-rest-spec.version}</version>
                                    <type>jar</type>
                                    <overWrite>false</overWrite>
                                    <includes>**/*.yml</includes>
                                </artifactItem>
                            </artifactItems>
                            <outputDirectory>${project.build.directory}/classes/external-api/admin-client/rest</outputDirectory>
                            <overWriteReleases>true</overWriteReleases>
                            <overWriteSnapshots>false</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- GENERATE REST APIs -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapigenerator.version}</version>
                <executions>
                    <execution>
                        <id>generate-admin-client-rest-api</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.build.directory}/classes/external-api/admin-client/rest/specs/openapi-rest.yml</inputSpec>
                            <generatorName>spring</generatorName>
                            <modelPackage>com.ferdonof.locki.external.admin.dto</modelPackage>
                            <generateSupportingFiles>false</generateSupportingFiles>
                            <skipOperationExample>true</skipOperationExample>
                            <generateApis>false</generateApis>
                            <generateModelTests>false</generateModelTests>
                            <generateApiTests>false</generateApiTests>
                            <modelNameSuffix>DTO</modelNameSuffix>
                            <library>spring-cloud</library>
                            <configOptions>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <dateLibrary>java8</dateLibrary>
                                <useOptional>true</useOptional>
                                <serializableModel>true</serializableModel>
                                <useSpringBoot3>true</useSpringBoot3>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>
</project>